### PR TITLE
Changes - Adding Georgia and make changes to some crawlers

### PR DESCRIPTION
**Pull request by matthewgomies**
Changes to :
Indiana_dearborn.py,  Indiana_vanderburgh.py, Iowa_black_hawk.py, Kansas_finney.py
Adding:
All Georgia and Indiana_newton.py

### CODE REVIEW

**Review by matthewgomies — COMMENTED** [review]
Minor fix for page index sequence for a few of Georgia crawlers

**Review by jborowitz — COMMENTED** [review]
I'm running a test of all the counties to make sure nothing is too different with the scrapers.

**Comment by jborowitz** [comment]
Matthew, I need the main() call of your georgia crawlers to access the row index variable instead of just using the row number. This moves our dependency from the ORDER OF THE ROWS IN THE CSV to a unique row number that we can add to. So like if we need to insert a new row, or sort the rows differently, it won't break all the other crawlers.

**Comment by matthewgomies** [comment]
Hi Jeff, sorry previously I forgot to change the main() call. I have updated the crawlers to include this. Thanks!

**Comment by jborowitz** [comment]
This looks great. There's something fussy about the csv that I will fix afterwards

**Pull request merged**
